// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Controller.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef ____Controller_h__
#define ____Controller_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace RoboCompController
{

class Controller;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompController::Controller>&);
::IceProxy::Ice::Object* upCast(::IceProxy::RoboCompController::Controller*);

}

}

namespace RoboCompController
{

class Controller;
bool operator==(const Controller&, const Controller&);
bool operator<(const Controller&, const Controller&);
::Ice::Object* upCast(::RoboCompController::Controller*);
typedef ::IceInternal::Handle< ::RoboCompController::Controller> ControllerPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::RoboCompController::Controller> ControllerPrx;
void __patch(ControllerPtr&, const ::Ice::ObjectPtr&);

}

namespace RoboCompController
{

struct TargetPose
{
    ::Ice::Float x;
    ::Ice::Float y;
    ::Ice::Float z;
};

struct NavState
{
    ::Ice::Long elapsedTime;
    ::std::string state;
    ::Ice::Long estimatedTime;
    ::Ice::Float distanceToTarget;
};

}

namespace Ice
{
template<>
struct StreamableTraits< ::RoboCompController::TargetPose>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 12;
    static const bool fixedLength = true;
};

template<class S>
struct StreamWriter< ::RoboCompController::TargetPose, S>
{
    static void write(S* __os, const ::RoboCompController::TargetPose& v)
    {
        __os->write(v.x);
        __os->write(v.y);
        __os->write(v.z);
    }
};

template<class S>
struct StreamReader< ::RoboCompController::TargetPose, S>
{
    static void read(S* __is, ::RoboCompController::TargetPose& v)
    {
        __is->read(v.x);
        __is->read(v.y);
        __is->read(v.z);
    }
};

template<>
struct StreamableTraits< ::RoboCompController::NavState>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 21;
    static const bool fixedLength = false;
};

template<class S>
struct StreamWriter< ::RoboCompController::NavState, S>
{
    static void write(S* __os, const ::RoboCompController::NavState& v)
    {
        __os->write(v.elapsedTime);
        __os->write(v.state);
        __os->write(v.estimatedTime);
        __os->write(v.distanceToTarget);
    }
};

template<class S>
struct StreamReader< ::RoboCompController::NavState, S>
{
    static void read(S* __is, ::RoboCompController::NavState& v)
    {
        __is->read(v.elapsedTime);
        __is->read(v.state);
        __is->read(v.estimatedTime);
        __is->read(v.distanceToTarget);
    }
};

}

namespace RoboCompController
{

class Callback_Controller_go_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Controller_go_Base> Callback_Controller_goPtr;

class Callback_Controller_getState_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Controller_getState_Base> Callback_Controller_getStatePtr;

class Callback_Controller_stop_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Controller_stop_Base> Callback_Controller_stopPtr;

}

namespace IceProxy
{

namespace RoboCompController
{

class Controller : virtual public ::IceProxy::Ice::Object
{
public:

    ::Ice::Float go(const ::RoboCompController::TargetPose& target)
    {
        return go(target, 0);
    }
    ::Ice::Float go(const ::RoboCompController::TargetPose& target, const ::Ice::Context& __ctx)
    {
        return go(target, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_go(const ::RoboCompController::TargetPose& target, const ::IceInternal::Function<void (::Ice::Float)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_go(target, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_go(const ::RoboCompController::TargetPose& target, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_go(target, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_go(const ::RoboCompController::TargetPose& target, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (::Ice::Float)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_go(target, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_go(const ::RoboCompController::TargetPose& target, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_go(target, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_go(const ::RoboCompController::TargetPose& target, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (::Ice::Float)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (::Ice::Float)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::RoboCompController::ControllerPrx __proxy = ::RoboCompController::ControllerPrx::uncheckedCast(__result->getProxy());
                ::Ice::Float __ret;
                try
                {
                    __ret = __proxy->end_go(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (::Ice::Float)> _response;
        };
        return begin_go(target, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_go(const ::RoboCompController::TargetPose& target)
    {
        return begin_go(target, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_go(const ::RoboCompController::TargetPose& target, const ::Ice::Context& __ctx)
    {
        return begin_go(target, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_go(const ::RoboCompController::TargetPose& target, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_go(target, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_go(const ::RoboCompController::TargetPose& target, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_go(target, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_go(const ::RoboCompController::TargetPose& target, const ::RoboCompController::Callback_Controller_goPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_go(target, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_go(const ::RoboCompController::TargetPose& target, const ::Ice::Context& __ctx, const ::RoboCompController::Callback_Controller_goPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_go(target, &__ctx, __del, __cookie);
    }

    ::Ice::Float end_go(const ::Ice::AsyncResultPtr&);
    
private:

    ::Ice::Float go(const ::RoboCompController::TargetPose&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_go(const ::RoboCompController::TargetPose&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::RoboCompController::NavState getState()
    {
        return getState(0);
    }
    ::RoboCompController::NavState getState(const ::Ice::Context& __ctx)
    {
        return getState(&__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_getState(const ::IceInternal::Function<void (const ::RoboCompController::NavState&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getState(0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_getState(const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getState(0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_getState(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::RoboCompController::NavState&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getState(&__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_getState(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getState(&__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_getState(const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::RoboCompController::NavState&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::RoboCompController::NavState&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::RoboCompController::ControllerPrx __proxy = ::RoboCompController::ControllerPrx::uncheckedCast(__result->getProxy());
                ::RoboCompController::NavState __ret;
                try
                {
                    __ret = __proxy->end_getState(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (const ::RoboCompController::NavState&)> _response;
        };
        return begin_getState(__ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_getState()
    {
        return begin_getState(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getState(const ::Ice::Context& __ctx)
    {
        return begin_getState(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getState(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getState(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getState(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getState(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getState(const ::RoboCompController::Callback_Controller_getStatePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getState(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getState(const ::Ice::Context& __ctx, const ::RoboCompController::Callback_Controller_getStatePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getState(&__ctx, __del, __cookie);
    }

    ::RoboCompController::NavState end_getState(const ::Ice::AsyncResultPtr&);
    
private:

    ::RoboCompController::NavState getState(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_getState(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void stop()
    {
        stop(0);
    }
    void stop(const ::Ice::Context& __ctx)
    {
        stop(&__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_stop(const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_stop(0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_stop(const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_stop(0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_stop(const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_stop(&__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_stop(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_stop(&__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_stop()
    {
        return begin_stop(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_stop(const ::Ice::Context& __ctx)
    {
        return begin_stop(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_stop(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_stop(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_stop(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_stop(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_stop(const ::RoboCompController::Callback_Controller_stopPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_stop(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_stop(const ::Ice::Context& __ctx, const ::RoboCompController::Callback_Controller_stopPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_stop(&__ctx, __del, __cookie);
    }

    void end_stop(const ::Ice::AsyncResultPtr&);
    
private:

    void stop(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_stop(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<Controller> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<Controller*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<Controller> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<Controller*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Controller> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<Controller*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<Controller> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<Controller*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Controller> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<Controller*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<Controller> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<Controller*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<Controller> ice_secure(bool __secure) const
    {
        return dynamic_cast<Controller*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<Controller> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<Controller*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<Controller> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<Controller*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<Controller> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<Controller*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<Controller> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<Controller*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<Controller> ice_twoway() const
    {
        return dynamic_cast<Controller*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<Controller> ice_oneway() const
    {
        return dynamic_cast<Controller*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<Controller> ice_batchOneway() const
    {
        return dynamic_cast<Controller*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<Controller> ice_datagram() const
    {
        return dynamic_cast<Controller*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<Controller> ice_batchDatagram() const
    {
        return dynamic_cast<Controller*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<Controller> ice_compress(bool __compress) const
    {
        return dynamic_cast<Controller*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<Controller> ice_timeout(int __timeout) const
    {
        return dynamic_cast<Controller*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<Controller> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<Controller*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<Controller> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<Controller*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace RoboCompController
{

class Controller : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual ::Ice::Float go(const ::RoboCompController::TargetPose&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual ::RoboCompController::NavState getState(const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void stop(const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace RoboCompController
{

class Controller : virtual public ::IceDelegate::RoboCompController::Controller,
                   virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual ::Ice::Float go(const ::RoboCompController::TargetPose&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::RoboCompController::NavState getState(const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void stop(const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace RoboCompController
{

class Controller : virtual public ::IceDelegate::RoboCompController::Controller,
                   virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual ::Ice::Float go(const ::RoboCompController::TargetPose&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::RoboCompController::NavState getState(const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void stop(const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace RoboCompController
{

class Controller : virtual public ::Ice::Object
{
public:

    typedef ControllerPrx ProxyType;
    typedef ControllerPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual ::Ice::Float go(const ::RoboCompController::TargetPose&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___go(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::RoboCompController::NavState getState(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___getState(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void stop(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___stop(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const Controller& l, const Controller& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const Controller& l, const Controller& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace RoboCompController
{

template<class T>
class CallbackNC_Controller_go : public Callback_Controller_go_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Float);

    CallbackNC_Controller_go(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::RoboCompController::ControllerPrx __proxy = ::RoboCompController::ControllerPrx::uncheckedCast(__result->getProxy());
        ::Ice::Float __ret;
        try
        {
            __ret = __proxy->end_go(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_Controller_goPtr
newCallback_Controller_go(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Float), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Controller_go<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Controller_goPtr
newCallback_Controller_go(T* instance, void (T::*cb)(::Ice::Float), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Controller_go<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_Controller_go : public Callback_Controller_go_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Float, const CT&);

    Callback_Controller_go(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::RoboCompController::ControllerPrx __proxy = ::RoboCompController::ControllerPrx::uncheckedCast(__result->getProxy());
        ::Ice::Float __ret;
        try
        {
            __ret = __proxy->end_go(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_Controller_goPtr
newCallback_Controller_go(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Float, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Controller_go<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Controller_goPtr
newCallback_Controller_go(T* instance, void (T::*cb)(::Ice::Float, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Controller_go<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_Controller_getState : public Callback_Controller_getState_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::RoboCompController::NavState&);

    CallbackNC_Controller_getState(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::RoboCompController::ControllerPrx __proxy = ::RoboCompController::ControllerPrx::uncheckedCast(__result->getProxy());
        ::RoboCompController::NavState __ret;
        try
        {
            __ret = __proxy->end_getState(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_Controller_getStatePtr
newCallback_Controller_getState(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::RoboCompController::NavState&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Controller_getState<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Controller_getStatePtr
newCallback_Controller_getState(T* instance, void (T::*cb)(const ::RoboCompController::NavState&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Controller_getState<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_Controller_getState : public Callback_Controller_getState_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::RoboCompController::NavState&, const CT&);

    Callback_Controller_getState(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::RoboCompController::ControllerPrx __proxy = ::RoboCompController::ControllerPrx::uncheckedCast(__result->getProxy());
        ::RoboCompController::NavState __ret;
        try
        {
            __ret = __proxy->end_getState(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_Controller_getStatePtr
newCallback_Controller_getState(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::RoboCompController::NavState&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Controller_getState<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Controller_getStatePtr
newCallback_Controller_getState(T* instance, void (T::*cb)(const ::RoboCompController::NavState&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Controller_getState<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_Controller_stop : public Callback_Controller_stop_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Controller_stop(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_Controller_stopPtr
newCallback_Controller_stop(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Controller_stop<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Controller_stopPtr
newCallback_Controller_stop(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Controller_stop<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_Controller_stopPtr
newCallback_Controller_stop(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Controller_stop<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Controller_stopPtr
newCallback_Controller_stop(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Controller_stop<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_Controller_stop : public Callback_Controller_stop_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Controller_stop(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_Controller_stopPtr
newCallback_Controller_stop(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Controller_stop<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Controller_stopPtr
newCallback_Controller_stop(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Controller_stop<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_Controller_stopPtr
newCallback_Controller_stop(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Controller_stop<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Controller_stopPtr
newCallback_Controller_stop(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Controller_stop<T, CT>(instance, 0, excb, sentcb);
}

}

#endif
